export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const READ_SINGLE_LESSON_REQUEST = 'READ_SINGLE_LESSON_REQUEST';
export const READ_SINGLE_LESSON_SUCCESS = 'READ_SINGLE_LESSON_SUCCESS';
export const READ_SINGLE_LESSON_FAILURE = 'READ_SINGLE_LESSON_FAILURE';

export const READ_BULK_LESSON_REQUEST = 'READ_BULK_LESSON_REQUEST';
export const READ_BULK_LESSON_SUCCESS = 'READ_BULK_LESSON_SUCCESS';
export const READ_BULK_LESSON_FAILURE = 'READ_BULK_LESSON_FAILURE';

