export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LESSON_CREATE_SUCCESS = 'LESSON_CREATE_SUCCESS';
export const LESSON_CREATE_FAIL = 'LESSON_CREATE_FAIL';
