export const CRUD_READ_ALL = "CRUD_READ_ALL";
export const CRUD_READ = "CRUD_READ";
export const CRUD_CREATE = "CRUD_CREATE";
export const CRUD_UPDATE = "CRUD_UPDATE";
export const CRUD_DELETE = "CRUD_DELETE";

export const FORM_DATA_UPDATE = "FORM_DATA_UPDATE";
export const FORM_DATA_UPDATE_NAME = "FORM_DATA_UPDATE_NAME";
export const FORM_DATA_UPDATE_LINK = "FORM_DATA_UPDATE_LINK";

export const DIABOLICAL_REDIRECT = "DIABOLICAL_REDIRECT";